Romajiによる変換後のデータをymlに追加
willnet/gimei pull request #69
Opened 2024-05-01 09:17 UTC by atolix

fix: https://github.com/willnet/gimei/issues/68

[Romaji](https://github.com/makimoto/romaji)で使用している標準ライブラリのnkfが、Ruby3.4からはdefault gemから外れます。 これによってromaji側でnkfを明示的に依存関係に指定しないと記載したissued通りにテストが失敗します。

そこで`romaji`メソッドでRomajiによる依存を無くす為に、yamlの各要素にローマ字変換後の値を追加しました。 変更後は`romaji`メソッドはyml配列の4番目を参照することになります。

2024-05-09 14:02 UTC, willnet requested changes
- unique_spec.rbで仮のテストデータを用意しているところが3要素のままでテストが失敗するようです
- romajiの依存がなくなるので[gimei/gimei.gemspec at main · willnet/gimei](https://github.com/willnet/gimei/blob/391e7a7ada6fc3327f034f88c1fca0645966a63e/gimei.gemspec#L20)を削除してもらえますか？

2024-05-12 12:03 UTC, atolix commented
@willnet 
ありがとうございます。修正分のコミットを追加しました。

2024-05-14 21:33 UTC, willnet approved these changes

2024-05-14 21:34 UTC, merged

2024-05-23 02:39 UTC, willnet commented
1.5.0リリースしました！ [Release v1.5.0 · willnet/gimei](https://github.com/willnet/gimei/releases/tag/v1.5.0)